name: Fetch Baidu Hot Search

on:
  schedule:
    # Runs daily at 23:00 UTC (07:00 China Standard Time)
    - cron: '0 23 * * *'
  workflow_dispatch:

permissions:
  contents: write

jobs:
  fetch:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests beautifulsoup4

      - name: Fetch Baidu hot search data
        run: |
          python scripts/fetch_baidu_hotsearch.py

      - name: Commit and push if there are changes
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: 'chore: update Baidu hot search data'
          branch: ${{ github.ref_name }}
